language: java
branches:
  only:
  - master
  - develop
install: true
cache:
  directories:
  - $HOME/.m2
script:
- git clone -b master https://github.com/nablarch/nablarch-ci-script.git $HOME/build-script/
  && chmod +x $HOME/build-script/travis-ci/*.sh
- $HOME/build-script/travis-ci/install-mvn-3.2.5.sh
- $HOME/build-script/travis-ci/prepare_travis_settings.sh
- $HOME/build-script/travis-ci/nablarch-profiles-mvn-deploy.sh -p travis
notifications:
  slack:
    secure: 5ynEGlJVX5Y+o9+ry9gCd7LrNe/y7XlgD146NBq2dyYi0tHIvzGw6mQsFeEjEyMEz+BTQUT+iPF9K71FlB9RQa3B8SeD9FssEj4tbtb3+VfIdkRKOYhLY5mdDnBPHbCD2ZIR53rEGVXXpfVlhouV9acN2qvXqILvbqNNIS1VLqJjJag5GyPNkSflv3OHg+ohnbecPbXGnq8lXKFToRE7cHxA00+2Vey7D90EARRcd+vQSg878GEgq6t5dbzbDRWyXO4l22GcMcPtZwL7DEeDAnzrHCUw/fsZkO+N1cSJImtDN1UaOmJ/BzXBbO9staVhrXB3Hc1fACjJSFmnENNu34PGEArcsjJTjAO1VryehCgMDlqTeUOj0YMAkCanRTWWs/AjQnmDBBGpGnZ6X3MX12JC9Ai5xXcndZGg3FmT/jbDfTfWff5A66zvvxNlDQ4QnbP94DDnI6/U5mzmkAMRVgbnD4STuaNGsKovSNsKAB5jlgvm1wsMDQlJNwO0h5YZXYd7Lb/0yh7j3NSZ8/OPAuRLUIVgVwtoCbLgAgKlwzZcT9oX6vPX9ObgtEMTtJE5HT4Cj6yQCRG8rGoq8meG2UyDg6NQGfOPpy+yqDDm6zDy2b3OXrPLREeu4y5awrp9KuZakHiZZVn8kza20xKVeS8Oe9GFa1Cztw4QMbZ52CY=
